spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mfort
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1

  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false


logging:
  level:
    org:
      hibernate:
        type:
          descriptor: